export const DynamicAsideMenuConfig = {
  items: [
    /* {
      title: 'Dashboard',
      root: true,
      icon: 'flaticon2-architecture-and-city',
      svg: './assets/media/svg/icons/Design/Layers.svg',
      page: '/dashboard',
      translate: 'MENU.DASHBOARD',
      bullet: 'dot',
    }, */

    { section: 'Applications' },
    // {
    //   title: 'eCommerce',
    //   bullet: 'dot',
    //   icon: 'flaticon2-list-2',
    //   svg: './assets/media/svg/icons/Shopping/Cart3.svg',
    //   root: true,
    //   permission: 'accessToECommerceModule',
    //   page: '/ecommerce',
    //   submenu: [
    //     {
    //       title: 'Customers',
    //       page: '/ecommerce/customers'
    //     },
    //     {
    //       title: 'Products',
    //       page: '/ecommerce/products'
    //     },
    //   ]
    // },
    
    {
      title: 'Manage Roles',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-role',
    },
    {
      title: 'Manage Users',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-users',
    },
    {
      title: 'Manage Subscriptions',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-subscription-pkgs',
    },
    {
      title: 'Manage District Admin',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-district-admin',
    },
    {
      title: 'Manage Schools',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-schools',
    },
    {
      title: 'Manage Tools',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-tools',
    },
    {
      title: 'Manage Ingredients',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-ingredients',
    },
    {
      title: 'Manage Nutrients',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-nutrients',
    },
    {
      title: 'Manage Culinary Techniques',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-culinary-techniques',
    },
    {
      title: 'Manage Countries',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-country',
    },
    {
      title: 'Manage Lessons',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-lessons',
    },
    {
      title: 'Manage Units Of Measurement',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-units-of-measurement',
    },
    {
      title: 'Manage Standards',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-standards',
    },
    {
      title: 'Manage Stamps',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-stamps',
    },
    {
      title: 'Manage Subjects',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-subjects',
    },  
    {
      title: 'Manage Issues Or Feedback',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-issuesFeedback',
    },
    {
      title: 'Manage Conversation Sentences',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-conversationSentence',
    },
    {
      title: 'Manage Health Hygiene',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-health-hygiene',
    },
    {
      title: 'Manage Image Drag Drop',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-image-drag-drop',
    },
    {
      title: 'Manage Image Flip Content',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-image-flip-content',
    },
    {
      title: 'Manage Discussion Forum',
      root: true,
      bullet: 'dot',
      icon: 'flaticon2-list-2',
      svg: './assets/media/svg/icons/Shopping/Cart3.svg',
      page: '/manage-discussion-forum',
    }
    
    // {
    //   title: 'User Profile',
    //   root: true,
    //   bullet: 'dot',
    //   icon: 'flaticon2-user-outline-symbol',
    //   svg: './assets/media/svg/icons/Communication/Add-user.svg',
    //   page: '/user-profile',
    // }
  ]
};
