export class LessionsDataContext {
    public static lessions: any = [
        {
            id: 1,
            lessonTitle: 'Test',
            createrName: 'Amit',
            reviewerName: 'Adnan Khan',
            learningObjForTeacher: 'learningObjForTeacher',
            learningObjForStudent: 'learningObjForStudent',
            greeting: 'greeting',
            linguisticDetails: 'linguisticDetails',
            chefIntroduction: ['chefIntroduction'],
            safteySteps: ['Category1'],
            safteyLevel: 'Adult Only',
            types: 'Category1',
            grade: 1,
            multiSenserActivity: 'multi',
            subject: 'Maths',
            cleanUpText: 'cleanUpText',
            funFactText: 'funFactText',
            socialStudiesFact: 'socialStudiesFact',
            links: ['links'],
            status: 'Active',
            prepration: [{ text: 'prepare test', link: 'link', estimatesTime: '2:30', toolsBigChef: ['teacher'], toolslittleChef: ['student'], desciption: [{ level: 'easy 1st and 2nd grade', text: 'description' }] }],
            cooking: [{ text: 'cooking steps test', link: 'link', estimatesTime: '2:30', toolsBigChef: ['teacher'], toolslittleChef: ['student'], desciption: [{ level: 'easy 1st and 2nd grade', text: 'description' }] }],
            serving: [{ text: 'serving test', link: 'link', desciption: [{ level: 'easy 1st and 2nd grade', text: 'description' }] }],
            description: [{ level: 'easy 1st and 2nd grade', text: 'description' }],
            tagsOrKeywords: 'tagsOrKeywords',
            recipes: {
                reciepsName: 'Recipe Name',
                country: 'India',
                alterNativeName: 'Race',
                estimatesTime: 2,
                serves: 1,
                ingredients: ['Name'],
                quantity: 1,
                unitOfMeasure: ['test'],
                linkOfImage: 'linkOfImage',
                quickBlurb: 'quickBlurb',
                toolsBigChef: ['teacher'],
                toolslittleChef: ['student'],
                techniques: ['tech1'],
                animationLink: 'link',
                dialogue: 'dialogue',
                holidays: 'holidays',
                description: [{ level: 'easy 1st and 2nd grade', text: 'description' }],
            },
            experiment: {
                experimentName: 'Experiment',
                ingredients: ['Name'],
                tools: ['tool1'],
                techniques: ['tech1'],
                steps: 'steps',
                description: [{ level: 'easy 1st and 2nd grade', text: 'description' }],
            },
            activity: {
                activityName: 'Activity Name1',
                image: 'image1',
                video: 'video1',
                link: 'link1',
                descriptions: [{ level: 'easy 1st and 2nd grade', text: 'description' }],
                question: [{ questionType: 'Essay type', answer: 'fsdfsd' }]
            },
            questions: [{
                questionName: 'question name one',
                hint: 'hint',
                standard: 'Six',
                answerType: 'Single selection',
                answer: [{ option: 'true', optionName: 'First Option' }, { option: 'second', optionName: 'Second Option' }, { option: 'third', optionName: 'Third Option' }, { option: 'four', optionName: 'Fourth Option' }],
                description: [{ level: 'easy 1st and 2nd grade', text: 'description dfsdf' }],
            },
            {
                questionName: 'question name two',
                hint: 'hint',
                standard: 'Six',
                answerType: 'Single selection',
                answer: [{ option: 'first', optionName: 'First Option' }, { option: 'second', optionName: 'Second Option' }, { option: 'third', optionName: 'Third Option' }, { option: 'four', optionName: 'Fourth Option' }],
                description: [{ level: 'easy 1st and 2nd grade', text: 'description cxc' }],
            }]
        }
    ];
}